{% set name = "negspacy" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/negspacy-{{ version }}.tar.gz
  sha256: c068bfbbcd28a63969733c3310a40e557a802b8fbb6b79cd724d6261860abb7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - spacy >=3.0.1,<4.0.0

test:
  imports:
    - negspacy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jenojp/negspacy
  summary: A spaCy pipeline object for negation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
